### ISSUE TITLE
Do you use Factory Girl callbacks?

### ISSUE THREAD

**Issue by ruralocity** [everydayrails/rails-5.0-rspec-3.5#2]
I'm wondering whether I should include a section on Factory Girl callbacks in the next version of [Everyday Rails Testing with RSpec](http://rspectutorial.com). If you've read the book, have you gone on to use these callbacks in your own projects? Or do you think the section is unnecessary?

**Comment by ristovskiv** [comment]
I think people should be introduced to as much as possible capabilities of Factory Girl (though they have a clear documentation). I don't really know if it will be advertising or not, but you can point to the link for a nice [24 min course](https://thoughtbot.com/upcase/videos/factory-girl) . Now I don't know for how long this link will be valid (as with most links), but since it's coming for `Upcase` which is `Thoughtbot's` I think it will last.

**Comment by andyw8** [comment]
I try to avoid using FactoryGirl callbacks, since they can cascade and cause a large number of queries to be run, slowing down the test suite. I'd rather make the setup explicit as part of test.

**Comment by JunichiIto** [comment]
I sometimes use FactoryGirl callbacks, but I think traits are more useful and important than callbacks, so please include them in the next version.

> Or do you think the section is unnecessary?

I think callbacks are important technique too, so they should remain in the book.

**Comment by ruralocity** [comment]
Thanks @ristovskiv @andyw8 @JunichiIto. I'm going to keep callbacks in the book, with stress that they can cause the problems that Andy mentioned. Junichi, yes, I am including traits.
